title: Attaching a Sense HAT
hero_image: images/sensehat-attach.png
description: How to attach a Sense HAT
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: false
interests: ""
technologies: "raspberry pi, sense hat"
steps:
  - title: Attach a Sense HAT
