---
title: Den Sense HAT befestigen
hero_image: images/sensehat-attach.png
description: So wird der Sense HAT befestigt
theme: red #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "raspberry pi, sense-hat"
steps:
  - 
    title: Befestige einen Sense HAT
