---
title: إرفاق لوحة Sense HAT
hero_image: images/sensehat-attach.png
description: كيفية إرفاق لوحة Sense HAT
theme: أحمر #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 1
curriculum:
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "raspberry pi, sense-hat"
steps:
  - 
    title: إرفاق لوحة Sense HAT
